#!/usr/bin/python3
# -*- coding: utf-8 -*-
import ujson
import queue
import locale
import curses

from zfs_monitor.collect_daemon import CollectDaemon


def main():
    locale.setlocale(locale.LC_ALL, '')

    data_queue = queue.Queue()
    daemon = CollectDaemon(data_queue)
    daemon.daemon = True
    daemon.start()
    try:
        while True:
            myscreen = curses.initscr()
            curses.start_color()
            curses.init_pair(1, curses.COLOR_BLUE, curses.COLOR_BLACK)
            curses.init_pair(2, curses.COLOR_RED, curses.COLOR_BLACK)
            curses.init_pair(3, curses.COLOR_MAGENTA, curses.COLOR_BLACK)
            curses.init_pair(4, curses.COLOR_CYAN, curses.COLOR_BLACK)
            curses.init_pair(5, curses.COLOR_GREEN, curses.COLOR_BLACK)
            curses.curs_set(0)
            myscreen.border(0)

            myscreen.clear()
            result = ujson.loads(data_queue.get())
            myscreen.addstr(1, 0, "ZFS real-time cache activity monitor",
                            curses.color_pair(1))
            myscreen.addstr(2, 0, "Updating every second", curses.color_pair(1))
            myscreen.addstr(3, 0, "Cache hits and misses:",
                            curses.color_pair(1))

            myscreen.addstr(4, 0, "ARC hits: %s" % result[1]["ARC_HIT"])
            
            myscreen.addstr(5, 0, "ARC misses: %s" % result[1]["ARC_MISS"])

            myscreen.addstr(6, 0, "ARC demand data hits: %s" %
                                  result[1]["ARC_DDH"])

            myscreen.addstr(7, 0, "ARC demand data misses: %s" %
                                  result[1]["ARC_DDM"])
            myscreen.addstr(8, 0, "ARC demand metadata hits: %s" %
                                  result[1]["ARC_DMH"])
            myscreen.addstr(9, 0, "ARC demand metadata misses: %s" %
                                  result[1]["ARC_DMM"])
            myscreen.addstr(10, 0, "ARC prefetch data hits: %s" %
                                   result[1]["ARC_PDH"])
            myscreen.addstr(11, 0, "ARC prefetch data misses: %s" %
                                   result[1]["ARC_PDM"])
            myscreen.addstr(12, 0, "ARC prefetch metadata hits: %s" %
                                   result[1]["ARC_PMH"])
            myscreen.addstr(13, 0, "ARC prefetch metadata misses: %s" %
                                   result[1]["ARC_PMM"])
            myscreen.addstr(15, 0, "L2ARC hits: %s" % result[1]["L2ARC_HIT"])
            myscreen.addstr(16, 0, "L2ARC misses: %s" % result[1]["L2ARC_MISS"])
            myscreen.addstr(18, 0, "ZFETCH hits: %s" % result[1]["ZFETCH_HIT"])
            myscreen.addstr(19, 0, "ZFETCH misses: %s" %
                                   result[1]["ZFETCH_MISS"])

            myscreen.addstr(21, 0, "ARC cache efficiency percentage:")

            myscreen.addstr(21, 60, "%s" % result[0]["ARC"],
                            curses.color_pair(color_choice(result[0]["ARC"])))

            myscreen.addstr(22, 0, "ARC demand data cache efficiency "
                                   "percentage:")
            myscreen.addstr(22, 60, "%s" % result[0]["ARCDD"],
                            curses.color_pair(color_choice(result[0]["ARCDD"])))

            myscreen.addstr(23, 0, "ARC prefetch data cache efficiency "
                                   "percentage:")
            myscreen.addstr(23, 60, "%s" % result[0]["ARCPD"],
                            curses.color_pair(color_choice(result[0]["ARCPD"])))

            myscreen.addstr(24, 0, "ARC prefetch metadata cache efficiency "
                                   "percentage:")
            myscreen.addstr(24, 60, "%s" % result[0]["ARCPM"],
                            curses.color_pair(color_choice(result[0]["ARCPM"])))

            myscreen.addstr(25, 0, "L2ARC cache efficiency percentage:")
            myscreen.addstr(25, 60, "%s" % result[0]["L2"],
                            curses.color_pair(color_choice(result[0]["L2"])))

            myscreen.addstr(26, 0, "ZFETCH cache efficiency percentage:")
            myscreen.addstr(26, 60, "%s" % result[0]["ZFETCH"],
                            curses.color_pair(color_choice(result[0]["ZFETCH"])))
            myscreen.refresh()
    except KeyboardInterrupt:
        curses.endwin()


def color_choice(value):
    if value <= 50:
        return 2
    elif 50 < value < 85:
        return 4
    else:
        return 5


if __name__ == '__main__':
    main()


